<?php

$lang['terms_and_conditions_desc'] = 'Welcome to www.Eachbuyer.com. By using the Website you agree to be bound by these Terms and Conditions and any Orders placed by you are bound by these Terms and Conditions. If you do not agree to these Terms and Conditions, please do not use the Website.';//null

$lang['terms'] = 'Terms of Use Agreement';//null

$lang['terms1'] = 'Application and Acceptance of Terms and Conditions.';//null
$lang['terms1_1'] = 'By accessing or using the Site, you hereby agree to accept the terms and conditions set forth in this Agreement as a User.';//null
$lang['terms1_2'] = 'Eachbuyer.com may amend this Agreement at any time by posting the amended and restated Agreement on the Site. The amended and restated Agreement shall be effective immediately upon posting. Posting by Eachbuyer.com of the amended and restated Agreement and your continued use of the Site shall be deemed to be acceptance of the amended terms. This Agreement may not otherwise be modified, except in writing by an authorized officer of Eachbuyer.com.';//null
$lang['terms1_3'] = 'When you visit Eachbuyer.com or send User requests (Client Service) to Eachbuyer.com, you are communicating with Eachbuyer.com electronically. You consent to receive communications from Eachbuyer.com electronically. Eachbuyer.com will communicate with you by e-mail or by posting notices on this site.';//null

$lang['terms2'] = 'User Generally.';//null
$lang['terms2_1'] = 'Users may use this Site solely for their own personal or internal purposes. Each User agrees that he shall not copy, reproduce or download any information, text, images, video clips, directories, files, databases or listings available on or through the Site (the "Eachbuyer.com Content") for the purpose of re-selling or re-distributing the Eachbuyer.com Content, mass mailing (via emails, wireless text messages, physical mail or otherwise), operating a business that competes with Eachbuyer.com, or otherwise commercially exploiting the Eachbuyer.com Content. Systematic retrieval of Eachbuyer.com Content from this Site to create or compile, directly or indirectly, a collection, compilation, database or directory (whether through robots, spiders, automatic devices or manual processes) without written permission from Eachbuyer.com is prohibited. In addition, use of the content or materials for any purpose not expressly permitted in this Agreement is prohibited.';//null
$lang['terms2_2'] = 'Eachbuyer.com reserves the right to limit, deny or create different access to the Site and its features with respect to different Users, or to change any of the features or introduce new features without prior notice. Each User acknowledges that inability to use the Site wholly or partially for whatever reason may have adverse effects on its business. Each User hereby agrees that in no event shall Eachbuyer.com be liable to the User for any inability to use the Site (whether due to disruption, limited access, changes to or termination of any features on the Site or otherwise), any delays, inaccuracies, errors or omissions with respect to any communications or transmission, or any damage (direct, indirect, consequential or otherwise) arising from the use of or inability to use the Site or any of its features.';//null
$lang['terms2_3'] = 'No User shall undertake any scheme to undermine the integrity of the computer systems or networks used by Eachbuyer.com and/or any other User and no User shall attempt to gain unauthorized access to such computer systems or networks.';//null
$lang['terms2_4'] = 'We urge that you read Eachbuyer.com\'s Privacy Policy which governs the protection and use of each User\'s information in the possession of Eachbuyer.com and/or its affiliates. Each User hereby accepts the Privacy Policy and any updates and amendments thereto. Each User acknowledges that Eachbuyer.com may change the Privacy Policy from time to time provided that Eachbuyer.com shall make available the updated version of the Privacy Policy on the Site at all times. Your continuation of use of the Site shall be deemed to be your acceptance of the Privacy Policy which is then displayed on the Site at the time of such use.';//null
$lang['terms2_5'] = 'As a condition of your access to and use of Eachbuyer.com, you agree that you will not use the Eachbuyer.com service to infringe the intellectual property rights or other legitimate rights of others in any way. Eachbuyer.com and/or its affiliates will in appropriate circumstances terminate the accounts of Users who are repeat infringers of the copyrights, or other intellectual property rights, or other legitimate rights of others. In addition, Eachbuyer.com and/or its affiliates reserves the right to terminate the account of a User upon any single infringement of the rights of others in conjunction with use of the Eachbuyer.com service, or if Eachbuyer.com believes that User\'s conduct is harmful to the interests of Eachbuyer.com, its affiliates, or other Users, or for any other reason in Eachbuyer.com\'s sole discretion, with or without cause.';//null

$lang['terms3'] = 'Registered Users';//null
$lang['terms3_1'] = 'Each User who has completed and submitted a registration form either online on the Site or offline by giving its information (such as name, address, telephone and fax number, email address, details of its business, etc.) to Eachbuyer.com or another Eachbuyer.com group company providing the relevant specific services is a registered User of the Site (a "Registered User"). An account ("Account") will be established for each Registered User and each Registered User will be assigned a User alias ("User ID") and password ("Password") for log-in access to his own Account.';//null
$lang['terms3_2'] = 'If the Registered User is a business entity, you represent that (a) you have the authority to bind the entity to this Agreement; (b) the address you use when registering is the principal place of business of such business entity; and (c) all other information submitted to Eachbuyer.com and its affiliates during the registration process is true, accurate, current and complete. For purposes of this provision, a branch or representative office will not be considered a separate entity and its principal place of business will be deemed to be that of its head office.';//null
$lang['terms3_3'] = 'By becoming a Registered User, you consent to the inclusion of your personal data in our UserDatabase. EACHBUYER may send emails to you or contact you otherwise through your personal data with whatever information EACHBUYER would like to convey to you.';//null
$lang['terms3_4'] = 'Eachbuyer.com or its affiliates may suspend or terminate a Registered User\'s Account at any time by giving no less than 24-hour notice to the Registered User; provided however, that notice is not required for such termination if (a) in Eachbuyer.com\'s determination, there is any breach of the provisions of this Agreement by the Registered User, or (b) Eachbuyer.com has reasonable grounds to suspect that any information provided by a Registered User is untrue, inaccurate or is not current or complete, or (c) Eachbuyer.com believes that the Registered User\'s actions may cause financial loss or legal liability to such Registered User.';//null
$lang['terms3_5'] = 'A Registered User may not sell, attempt to sell, offer to sell, give, assign or otherwise transfer an Account, User ID or Password to a third party without the prior written consent of Eachbuyer.com. Eachbuyer.com may suspend or terminate the Account of a Registered User or the transferee of a Registered User in the event of a sale, offer to sell, gift, assignment or transfer in violation of this Section.';//null
$lang['terms3_6'] = 'Notwithstanding Section 3.1 above, Eachbuyer.com may refuse registration and deny the issuance of an Account and associated User ID and Password to any User for whatever reason.';//null


$lang['terms4'] = 'Relationship between Users &amp; EACHBUYER';//null
$lang['terms4_1'] = 'Eachbuyer.com is a global online retail store owned by GBC leader Ltd . It sells and delivers Products directly to consumers around the world.';//null
$lang['terms4_2'] = 'Although we try to ensure all our Product\'s prices displayed in the Product Description are accurate, errors may sometimes occur. If we discover an error in the price of a Product you have ordered we will be unable to accept your Order and shall contact you as soon as possible in order to give the option of either reconfirming your Order at the correct price or cancelling it. If we are unable to contact you, we will treat your Order in respect of the incorrectly priced item as cancelled.';//null
$lang['terms4_3'] = 'The risks of purchase transactions when using the Site to conduct transactions shall include misrepresentation of Products and services, unsatisfactory quality, failure to meet specifications, defective or dangerous Products, delay or default in delivery and transportation accidents. All of the foregoing risks are hereafter referred to as "Transaction Risks." Eachbuyer.com will bear and take fully responsibility of all the Transaction risks until the goods are delivered to User in perfect. But when Users submit the issues that may arise as result of or in connection with the transaction risks on the website, we will solve the problem in due course per User\'s requirement.';//null

$lang['terms5'] = 'Intellectual Property Rights (IPR) Protection Policy';//null
$lang['terms5_desc1'] = 'For all Products offered by Eachbuyer, Eachbuyer guarantees that no intellectual or property rights are infringed. Eachbuyer will not sell any branded Products without official reseller agreements with brands.Eachbuyer.com takes appropriate action where necessary to uphold and recognize all relevant State, Federal and International laws in connection with material that is claimed to be infringing any trademark, copyright, patent and all or any other Intellectual Property laws.If you are an intellectual property rights owner and you believe thatEachbuyer.com sells, offers for sale, or makes available goods and/or services that infringe your intellectual property rights, please send the following information in its entirety to cs@eachbuyer.com<br>Information required';//null
$lang['terms5_1'] = 'An electronic or physical signature of the person authorized to act on behalf of the owner of an exclusive that is allegedly infringed;';//null
$lang['terms5_2'] = 'A description of the allegedly infringing work or material;';//null
$lang['terms5_3'] = 'A description of where the allegedly infringing material is located on the site (Product(s) URL);';//null
$lang['terms5_4'] = 'Information reasonably sufficient to allow us to contact you, such as your address, telephone number and e-mail address;';//null
$lang['terms5_5'] = 'A statement by you that you have a good faith belief that the disputed use of the material is not authorized by the copyright or other proprietary right owner, its agent, or the law;';//null
$lang['terms5_6'] = 'Identification of the intellectual property rights that you claim are infringed by the Website (e.g. "XYZ copyright", "ABC trademark, Reg. No. 123456, registered 1/1/04",etc); and';//null
$lang['terms5_7'] = 'A statement by you that the above information and notification is accurate, and under penalty of perjury, that you are the copyright owner or authorized to act on behalf of the owner whose exclusive right is allegedly infringed.';//null
$lang['terms5_desc2'] = 'If you need to send us paper documents, please send the related Products and paper documents to the following address: 28 ROCKWELL COURT, THE GATEWAY, WATFORD, ENGLAND. So that EACHBUYER can receive and dispose them in time. Please note that this is the only legal address on Eachbuyer.com that deals with Product infringement.';//null


$lang['terms6'] = 'Limitation of Liability';//null
$lang['terms6_1'] = 'We make no warranty that the Website will meet your requirements or will be uninterrupted, timely or error-free, that defects will be corrected, or that the site or the server that makes it available are free of viruses or bugs or represents the full functionality, accuracy, and reliability of the Website. We will not be responsible or liable to you for any loss of material uploaded or transmitted through the Website.';//null
$lang['terms6_2'] = 'Eachbuyer is responsible for warranties in relation with the Products to the fullest extent permissible under applicable law without affecting your statutory rights as a consumer.';//null
$lang['terms6_3'] = 'Any material downloaded or otherwise obtained through the Site is done at each User\'s sole discretion and risk and each User is solely responsible for any damage to its computer system or loss of data that results from the download of any such material. No advice or information, whether oral or written, obtained by any User from Eachbuyer.com or through or from the Site shall create any warranty not expressly stated herein.';//null
$lang['terms6_4'] = 'Under no circumstances shall Eachbuyer.com be held liable for any delay or failure or disruption of the content or services delivered through the Site resulting directly or indirectly from acts of nature, forces or causes beyond its reasonable control, including without limitation, Internet failures, computer, telecommunications or any other equipment failures, electrical power failures, strikes, labor disputes, riots, insurrections, civil disturbances, shortages of labor or materials, fires, flood, storms, explosions, acts of God, war, governmental actions, orders of domestic or foreign courts or tribunals.';//null
$lang['terms6_5'] = 'Each User hereby agrees to indemnify and save Eachbuyer.com, its affiliates, directors, officers and employees harmless, from any and all losses, claims, liabilities (including legal costs on a full indemnity basis) which may arise from such User\'s use of the Site (including but not limited to the display of such User\'s information on the Site) or from its breach of any of the terms and conditions of this Agreement. Each User hereby further agrees to indemnify and save Eachbuyer.com, its affiliates, directors, officers and employees harmless, from any and all losses, claims, liabilities (including legal costs on a full indemnity basis) which may arise from User\'s breach of any representations and warranties made by User to Eachbuyer.com. Each User hereby further agrees to indemnify and save Eachbuyer.com, its affiliates, directors, officers and employees harmless, from any and all losses, claims, liabilities (including legal costs on a full indemnity basis) which may arise, directly or indirectly, as a result of any claims asserted by Third Party Rights claimants. Each User hereby further agrees that Eachbuyer.com is not responsible and shall have no liability to it, for any material posted by others; including defamatory, offensive or illicit material and that the risk of damages from such material rests entirely with each User. Eachbuyer.com reserves the right, at its own expense, to assume the exclusive defense and control of any matter otherwise subject to indemnification by you, in which event you shall cooperate with Eachbuyer.com in asserting any available defenses.';//null
$lang['terms6_6'] = 'Eachbuyer.com shall not be liable for any special, direct, indirect, punitive, incidental or consequential damages or any damages whatsoever (including business interruption), whether in contract, negligence, tort or otherwise or any other damages resulting from any of the following:
		<br>the use or the inability to use the Site;
		<br>statements or conduct of any User of the Site; or any matters relating to Premium Services however arising, including negligence.';//null
$lang['terms6_7'] = 'Notwithstanding any of the foregoing provisions, the aggregate liability of Eachbuyer.com, its employees, agents, affiliates, representatives or anyone acting on its behalf with respect to each User for all claims arising from the use of the Site or the Eachbuyer.com service shall be limited to the greater of (a) the amount of fees the User pays to Eachbuyer.com or its affiliates in the 12 months period prior to the action giving rise to liability and (b) £100. The preceding sentence shall not preclude the requirement by the User to prove actual damages. All claims arising from the use of the Site or the Eachbuyer.com service must be filed within one (1) year from the date the cause of action arose.';//null


$lang['terms7'] = 'Intellectual Property Rights';//null
$lang['terms7_1'] = 'Eachbuyer.com is the sole owner or lawful licensee of all the rights to the Site and the EACHBUYER Content. The Site and Eachbuyer.com Content embody trade secrets and intellectual property rights protected under worldwide copyright and other laws. All title, ownership and intellectual property rights in the Site and Eachbuyer.com Content shall remain with Eachbuyer.com, its affiliates or licensors of the Eachbuyer.com Content, as the case may be. All rights not otherwise claimed under this Agreement or by Eachbuyer.com are hereby reserved.';//null


$lang['terms8'] = 'General';//null
$lang['terms8_1'] = 'This Agreement and the Privacy Policy constitute the entire agreement between you the User and Eachbuyer.com with respect to the use of the Site, superseding any prior written or oral agreements in relation to the same subject matter herein.';//null
$lang['terms8_2'] = 'If any provision of this Agreement is held to be invalid or unenforceable, such provision shall be struck and the remaining provisions shall be enforced.';//null
$lang['terms8_3'] = 'Headings are for reference purposes only and in no way define, limit, construe or describe the scope or extent of such section.';//null
$lang['terms8_4'] = 'Eachbuyer.com\'s failure to enforce any right or failure to act with respect to any breach by a User under this Agreement will not waive that right nor waives Eachbuyer.com\'s right to act with respect with subsequent or similar breaches.';//null
$lang['terms8_5'] = 'Eachbuyer.com shall have the right to assign this Agreement (including all of its rights, titles, benefits, interests, and obligations and duties in this Agreement). The User may not assign, in whole or part, this Agreement to any person or entity.';//null
$lang['terms8_6'] = 'This Agreement shall be governed by the laws of England without regard to its conflict of law provisions. The parties to this Agreement hereby submit to the exclusive jurisdiction of the courts of England.';//null
$lang['terms8_7'] = 'If there is any conflict between the English version and another language version of this Agreement, the English language version shall prevail.';//null


$lang['terms9'] = 'Return Policy';//null
$lang['terms9_desc1'] = 'Please review these policies carefully as they are the terms of sale that govern your purchases at Eachbuyer.com (hereinafter known as EACHBUYER). They set out your rights and obligations with respect to your purchases, including important limitations and exclusions. Your placement of an Order at EACHBUYER constitutes your agreement that these policies apply to the Order, so be certain you understand them before you place your Order.';//null

$lang['terms9_doa_item'] = 'Return DOA (Dead on Arrival) Item';//null
$lang['terms9_doa_item1'] = 'Any Products, dead on arrival (incorrect usage excluded) within 45 days after shipment.';//null
$lang['terms9_doa_item2'] = 'In this case, please kindly provide us with proof as below:';//null
$lang['terms9_doa_item3'] = 'The photos of original EACHBUYER package with front and back sides';//null
$lang['terms9_doa_item4'] = 'The photos or video of the defective item(s)';//null
$lang['terms9_doa_item5'] = 'The photos, video or screenshot showing the malfunction of the defective item(s)';//null
$lang['terms9_doa_item6'] = 'In a DOA Situation: a reimbursement for return shipping fees is available, provided that:';//null
$lang['terms9_doa_item7'] = 'Return the item(s) by ordinary mail (the least expensive way) with tracking number to the nearest Product Drop Off Box (see details below); If the mail service with tracking number costs more, you may choose the one without tracking. Please be sure to keep the shipping receipt with you after return. We will process for you upon receiving the screen shot of your receipt.';//null
$lang['terms9_doa_item8'] = 'The return shipping fee is less than 60% of the defective item(s) value, and also less than $40 (USD), we will cover the actual postage (according to the receipt you provided). If the return shipping fee exceeds the limit above, please contact our CS staff to further confirm it.';//null

$lang['terms9_defective_item'] = 'Return Defective Item';//null
$lang['terms9_defective_item1'] = 'We will try our best to make sure the Products shipped to you are in the best condition. In case your Product (only for items without Special Warranty terms in the Product description and physical damage or incorrect use excluded) turns out to be defective:';//null
$lang['terms9_defective_item2'] = 'If the defect is not caused by you, we will pay all necessary shipping fees for returning the defected Product to us and for sending the replaced one to you; or If the defect is caused by you, you will pay necessary shipping fees for returning the defected Product to us and for sending the replaced one to you';//null

$lang['terms9_90days_item'] = 'Within 90 days from shipment';//null
$lang['terms9_90days_item1'] = 'Policy: Upon being returned, the defective item will only be replaced. Detail: If the Product turns out to be defective within 90 days from shipment, User may mail the Products back to us. We will still try to exchange your defective Products for a brand new one where possible.';//null

$lang['terms9_91_365days_item'] = 'Between 91 days and 365 days from shipment';//null
$lang['terms9_91_365days_item1'] = 'Policy: Upon being returned, the defective item will be forwarded to the factory for repair. Detail: Should the item become defective within 365 days from shipment, Users will still be allowed to send the Product back to us. We will help by forwarding the item to the manufacturer for repair or replacement.';//null

$lang['terms9_incorrect_item'] = 'Return Incorrect Item Received';//null
$lang['terms9_incorrect_item1'] = 'If the item you received is completely different from the one you ordered, please contact us via our Client Service Express and provide us the picture proof of the error.';//null
$lang['terms9_incorrect_item2'] = 'If return is necessary, replacement plus shipping cost reimbursement will be issued to you on receipt of return proof. Please be sure that the incorrect item you return is in the original package and the merchandise is in the same condition in which it was received.';//null
$lang['terms9_incorrect_item3'] = 'For the incorrect item, if you are able to find a use of it and prefer to keep it, you may suggest that to us and we will offer you a certain discount for buying it.';//null
$lang['terms9_incorrect_item4'] = 'After receiving the incorrect Product, please kindly provide us with proof as below:';//null

$lang['terms9_photos_video_item'] = 'The photos or video of the incorrect item(s)';//null
$lang['terms9_photos_video_item1'] = 'The photos, video or screen shot showing the malfunction of the defective item(s)';//null
$lang['terms9_photos_video_item2'] = 'Because different batches of the Products are supplied, the item logo or packaging you received may vary from the one displayed on our website. If all the functions and appearance of the Product prove to be correct, please understand that this case will not be included in this policy.';//null

$lang['terms9_unstatisfactory_products'] = 'Return Unsatisfactory Products';//null
$lang['terms9_unstatisfactory_products1'] = 'If you are not happy for any reason with your purchase, then just return it within 14 days of receipt for a full refund or an exchange.';//null
$lang['terms9_unstatisfactory_products2'] = '<strong>Note</strong>: Please contact with our ClientService department before you send the Product back to avoid exchange, refund, or repair delays.';//null

$lang['terms9_desc2'] = 'Underwear, customized Products, one-time use Products and lingerie are not available for return except in regards to quality issues. In such a case, the quality problem must be reported within 48 hours of delivery receipt with pictures clearly showing the defect. We do not accept returns because of wrong sizing or underwhelmed expectations. Please consult our sizing charts before ordering or consult a Client Service representative in case of doubt.';//null

$lang['terms10'] = 'Definitions:';//null
$lang['terms10_1'] = 'Terms and Conditions" means these terms and conditions.';//null
$lang['terms10_2'] = 'We", "us" or "Eachbuyer""Eachbuyer.com" means GBC Leader Ltd., as the context may require. Please note, that when arranging delivery of your Order, Eachbuyer may instruct a third party courier or postal carrier to deliver it to you. However, Eachbuyer will ultimately be responsible for managing the delivery of your Order, so for the purposes of these Terms and Conditions, all references to "we", "us", or "Eachbuyer" "Eachbuyer.com", will be taken to include such third parties.';//null
$lang['terms10_3'] = 'Website" or "Site" means the website located at www.Eachbuyer.com or any subsequent URL which may replace it.';//null
$lang['terms10_4'] = 'Users""each user" means the users of the Website collectively.';//null
$lang['terms10_5'] = 'You" means a user of this Website.';//null
$lang['terms10_6'] = 'Order" means an online transaction made by you via the Website for one or more Products, to which these Terms and Conditions apply.';//null
$lang['terms10_7'] = 'Product" means a product displayed for sale on the Website.';//null
